[package]
name = "show-files"
version = "0.7.1"
edition = "2021"

[[bin]]
name = "sf"
path = "src/main.rs"

[dependencies]
atty = "0.2.14"
clap = { version = "3.0.13", features = ["unicode", "wrap_help", "cargo"] }
glob = "0.3.0"
terminal_size = "0.1.17"
