[package]
name = "show-files"
version = "0.6.2"
edition = "2018"

[[bin]]
name = "sf"
path = "src/main.rs"

[dependencies]
atty = "0.2.14"
clap = "3.0.0-beta.2"
glob = "0.3.0"
terminal_size = "0.1.17"
